### ISSUE TITLE
Replace `add`, `update` commands with `sync`, `config` commands

### ISSUE THREAD

**Issue by mofeing** [bsc-quantic/pypickup#25]
From the very beginning we have seen some frictions with the semantics behind the `add` and `update` commands. One example is the discussion in #20.

My proposal is to
1. Implement modifiers/filters as entrypoints
2. Refactor `add`, `update` functionality to `sync`,`config` commands

The `sync` command would fetch a list of _filenames_ from PyPI and
1. If the package is not present in the local cache, then create a new subdir, a new `index.html`, apply default filters (e.g. dev versions filter) unless modifier flags are present and download them. If modifier flags are present, store them in the `index.html` metadata.
2. If the package is present, then load configuration/filters and list of already downloaded files from `index.html`. Afterwards, apply the loaded filters to the list of filenames downloaded from PyPI, compute the diff with the list of local files and download the result. If modifier flags are present, then override default filters.

## Roadmap

- [ ] New entry-point group for filters `pypickup.filter`
  - [ ] Implement `dev` version filter as entrypoint
  - [ ] Implement alpha, beta version filter as entrypoint
  - [ ] Implement wheels filter as entrypoint
- [ ] Store package configuration (i.e. filters) in packages' `index.html` as metadata (#20)
- [ ] New `config` command to check and edit packages' `index.html` metadata
- [ ] New `sync` command to fetch packages from PyPI
  - Acts like `add` if package **is not** in local cache
  - Acts like `update` if package **is** in local cache
  - May add some filters as default

**Comment by HerManNav** [comment]
Commit 02987741887314259ba5517fce4d8265faffb916
